# Generated by Django 5.0.4 on 2024-05-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('grade', models.IntegerField(default=10)),
                ('section', models.CharField(max_length=1)),
                ('gender', models.CharField(max_length=10)),
                ('instagram', models.CharField(max_length=200)),
                ('whatsapp', models.CharField(max_length=200)),
                ('snapchat', models.CharField(max_length=200)),
                ('other', models.CharField(max_length=200)),
                ('interests', models.CharField(max_length=300)),
                ('bio', models.CharField(max_length=300)),
            ],
        ),
    ]
