# Generated by Django 5.0.4 on 2024-05-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinder', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='instagram',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='other',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='snapchat',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(default='', max_length=200),
        ),
    ]
