# Generated by Django 5.0.4 on 2024-05-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinder', '0004_alter_user_instagram_alter_user_other_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='other',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='snapchat',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
